blog/urls.py
from django.conf.urls import url 
import os
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'blog'
urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^Tag/(?P<pk>[0-9]+)/$', views.TagView, name='Tag'),
    url(r'^uploadfile$', views.upload, name='upload'),
    url(r'^Editor/$', views.Editor, name='Editor'),
]

media_root = os.path.join(settings.BASE_DIR,'upload')
urlpatterns += static('/upload/', document_root=media_root)

blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),  
    url(r'', include('blog.urls')), 
    url(r'', include('comments.urls')),

]

comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User 
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Tag(models.Model): 
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Post(models.Model): 
    title = models.CharField(max_length=70)#文章標題
    body = models.TextField()#內文
    excerpt = models.CharField(max_length=200, blank=True)#摘要
    created_time = models.DateTimeField()#創建時間
    modified_time = models.DateTimeField()#更新時間
    category = models.ForeignKey(Category)#類別
    tags = models.ManyToManyField(Tag, blank=True)#標籤
    author = models.ForeignKey(User)#作者
    views = models.PositiveIntegerField(default=0, editable=False)
    def get_absolute_url(self): 
        return reverse('blog:detail', kwargs={'pk': self.pk})
    
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

class UpFile(models.Model):
    up_file = models.FileField(upload_to='upload/')

    def __unicode__(self):
        return self.up_file

comments/models.py
from django.db import models
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blog.Post')

comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

blog/views.py
from django.shortcuts import render,get_object_or_404,HttpResponse
from .models import Post ,Category,Tag,UpFile

from comments.forms import CommentForm
import markdown
from django import forms
import json

def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})

def detail(request, pk): 
    post = get_object_or_404(Post, pk=pk)
    post.increase_views() 
    form = CommentForm()
    comment_list = post.comment_set.all()#_set:針對一對多的查詢語法

    post.body = markdown.markdown(post.body,
                                  extensions=[ 'markdown.extensions.extra',
                                  'markdown.extensions.codehilite',
                                   'markdown.extensions.toc', ])
    context = {'post': post,
               'form': form,
               'comment_list': comment_list
               }

    return render(request, 'blog/detail.html', context=context)

def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month ).order_by('-created_time') 
    return render(request, 'blog/index.html', context={'post_list': post_list})

def category(request, pk): #記得在前面import Category
   cate = get_object_or_404(Category, pk=pk) 
   post_list = Post.objects.filter(category=cate).order_by('-created_time') 
   return render(request, 'blog/index.html', context={'post_list': post_list})

def TagView(request, pk): #記得在前面import Tag
   Tag_obj = get_object_or_404(Tag, pk=pk)
   post_list = Post.objects.filter(tags=Tag_obj).order_by('-created_time') 
   return render(request, 'blog/index.html', context={'post_list': post_list})


class UpFiles(forms.Form):
    upfile = forms.FileField()
    
def Editor(request):
    return render(request, 'blog/Editor.html')

def upload(request):
    if request.method == "POST":
        up = UpFiles(request.POST, request.FILES)
        cc = UpFile(up_file=request.FILES['file'])
        cc.save()
        url = 'http://127.0.0.1/' + str(cc.up_file)
        resp = {'success':1,'message': "6666",'url': url}
        return HttpResponse(json.dumps(resp), content_type="application/json")
    else:
        print("NO")
        resp = {'success': 0, 'message': "error meth"}
        return HttpResponse(json.dumps(resp), content_type="application/json")
    return render(request, 'blog/Editor.html')

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post
from .models import Comment
from .forms import CommentForm
def post_comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk) 
    

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid(): 
            comment = form.save(commit=False)
            comment.post = post 
            comment.save()
            return redirect(post)
        else:
            comment_list = post.comment_set.all()
            context = {'post': post,
                            'form': form,
                            'comment_list': comment_list
                            }
            return render(request, 'blog/detail.html', context=context)
    return redirect(post)

templates/base.html
{% load staticfiles %}
{% load blog_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>Huang Steve's Blog</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static '/blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static '/blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static '/blog/css/highlights/github.css' %}">
    <link rel="stylesheet" href="{% static '/blog/css/Blog.css' %}">
    

    <!-- js -->
    <script src="{% static '/blog/js/commentTyping.js' %}"></script>
    <script src="{% static '/blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static '/blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/blog/js/pace.min.js' %}"></script>
    <script src="{% static '/blog/js/modernizr.custom.js' %}"></script>

</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}">Huang Steve's Blog</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首頁">首頁</a></li>
                            <li class="cl-effect-11"><a data-hover="關於我">關於我</a></li>
                            <li class="cl-effect-11"><a data-hover="聯繫">聯繫</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>


<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
              {% block main %}
              {% endblock main %} 
            </main>
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                      {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{post.title}}  </a>
                        </li>
                       {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">歸檔</h3>
                    {% archives as date_list %}
                        <ul>
                          {% for date in date_list %}
                            <li>
                                <a href="/archives/{{date.year}}/{{date.month}}/">{{date.year}} 年 {{date.month}} 月</a>
                            </li>
                          {% empty %}
                            	暫無歸檔
                          {% endfor %}  
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分類</h3>
                    {% get_categories as category_list %}
                        <ul>
                          {% for category in category_list %}
                            <li>
                                <a href="/category/{{category.pk}}/">{{ category.name }} </a>
                            </li>
                          {% empty %}
                            	暫無分類
                          {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">標籤雲</h3>
                        {% get_tags as tag_list %}
                        <ul>
                          {% for tag in tag_list %}
                            <li>
                                <a href="/Tag/{{tag.pk}}/">{{tag.name}}</a>
                            </li>
                          {% empty %}
                            	暫無標籤
                          {% endfor %}
                        </ul>

                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
<!--                這裡可以放版權相關 -->
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首頁</a></li>
            <li><a >關於我</a></li>
            <li><a >聯繫我</a></li>
        </ul>
    </nav>
</div>

</body>
</html>

templates/blog/Editor.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8" />
        <title>Editor</title>
        <link rel="stylesheet" href={% static 'Editor/css/style.css' %} />
        <link rel="stylesheet" href={% static 'Editor/css/editormd.css' %} />
        <link rel="shortcut icon" href="https://pandao.github.io/editor.md/favicon.ico" type="image/x-icon" />
    </head>

    <body>
        <div id="layout">
            <header>
                <h1>Simple example</h1>
            </header>
            <div id="test-editormd">
                <textarea style="display:none;"></textarea>
            </div>
        </div>
        <script src={% static 'Editor/jquery.min.js' %}></script>
        <script src={% static 'Editor/editormd.min.js' %}></script>
        <script type="text/javascript">
			var testEditor;

            $(function() {
                testEditor = editormd("test-editormd", {
                    width   : "90%",
                    height  : 640,
                    syncScrolling : "single",
                    path    : "/static/Editor/lib/",
                    //打开上传图片
                    imageUpload : true,
                    imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
                    imageUploadURL : "/uploadfile",
                    saveHTMLToTextarea : true,
                    toolbarIcons : function() {
                    // Or return editormd.toolbarModes[name]; // full, simple, mini
                    // Using "||" set icons align right.
                    //return ["undo", "redo", "|", "bold", "hr", "|", "preview", "watch", "|", "fullscreen", "file", "faicon", "||", "watch", "fullscreen", "preview"]
                    return  ["bold", "del", "italic", "hr", "image", "table", "datetime", "|", "preview", "watch", "|", "fullscreen"];
                    },

                    //下面这一行将使用dark主题
                    editorTheme: "pastel-on-dark",
                    theme: "gray",
                    previewTheme : "dark"
                    //editor.md期望得到一个json格式的上传后的返回值，格式是这样的：
                      /*
                      {
                          success : 0 | 1,           // 0 表示上传失败，1 表示上传成功
                          message : "提示的信息，上传成功或上传失败及错误信息等。",
                          url     : "图片地址"        // 上传成功时才返回
                      }
  */
                });
            });
        </script>
    </body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
            <article class="post post-1">
                <header class="entry-header">
                    <h1 class="entry-title">{{post.title}}</h1>
                    <div class="entry-meta">
                        <span class="post-category"><a href="#">{{post.title}}</a></span>
                        <span class="post-date"><a href="#"><time class="entry-date"    datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                        <span class="post-author"><a href="#">{{ post.author }}</a></span>
                        <span class="comments-link"><a href="#">{{ post.comment_set.count }} 評論</a></span>
                        <span class="views-count"><a href="#">{{ post.views }} 閱讀</a></span>
                    </div>    </header>
                <div class="entry-content clearfix"> 
                   {{post.body|safe}}    
                </div>
            </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>發表評論</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="id_name">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="id_email">Email：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="id_url">網址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="id_comment">評論：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">發表</button>
                            </div>
                        </div>
                </form>
                    <div class="comment-list-panel">
                        <h3>評論列表，共 <span>{{ post.comment_set.count }}</span> 條評論</h3>
                        <ul class="comment-list list-unstyled">
                          {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{comment.name}}</span>
                                <time class="submit-date">{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            目前無評論
                           {% endfor %}
                        </ul>
                    </div>
                </section>
            </main>
 {% endblock main %} 

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
    {% for post in post_list %}
    <article class="post post-{{post.pk}}"> 
       <header class="entry-header">
            <h1 class="entry-title">
                <a href="single.html">{{post.title}}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{post.category.name}}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"  datetime="{{ post.created_time }}">{{ post.created_time }}</time>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">{{ post.comment_set.count }} 評論</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 閱讀</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{ post.excerpt }}</p>
            <div class="read-more cl-effect-14"> 
               <a href="{{ post.get_absolute_url }}" class="more-link">繼續閱讀 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% empty %}
    目前無文章
    {% endfor %}
{% endblock main %}
    